import { getIncidentStats, getSettlementStats } from "@/lib/analytics/metrics";
import { formatINR, formatPercent, formatShortINR } from "@/lib/utils";
import type { AuditEvent } from "@/lib/types";

/**
 * Audit trail — stage 10's evidence base.
 *
 * Every event carries the same triple: who acted, what happened, what the
 * result was, against a referenced entity. An auditor should be able to
 * reconstruct the whole chain — detection, investigation, recommendation,
 * approval, gateway call, failure, fallback, recovery — without reading any
 * other screen.
 *
 * These are the events produced before the presenter touches anything. Events
 * generated by executing an action are appended by the executor at run time.
 */
export function getBaseAuditEvents(): AuditEvent[] {
  const s = getIncidentStats();
  const st = getSettlementStats();

  const events: AuditEvent[] = [
    // ---- today: settlement ------------------------------------------------
    {
      id: "aud_0601",
      at: "2026-02-18T06:40:18+05:30",
      actor: "ai",
      event: "Settlement variance detected",
      detail: `${formatShortINR(st.varianceAmount)} gap between captured value and settled value on ${st.discrepancy?.utr ?? "cycle"}`,
      refType: "settlement",
      refId: st.discrepancy?.id ?? "setl",
      result: "info",
    },
    {
      id: "aud_0602",
      at: "2026-02-18T06:41:02+05:30",
      actor: "ai",
      event: "Investigation created",
      detail: "inv_1045 — settlement discrepancy",
      refType: "investigation",
      refId: "inv_1045",
      result: "ok",
    },
    {
      id: "aud_0603",
      at: "2026-02-18T06:44:01+05:30",
      actor: "ai",
      event: "Recommendation generated",
      detail: "File a reconciliation request with the transaction-level match attached",
      refType: "action",
      refId: "act_2044",
      result: "ok",
    },

    // ---- today: refunds ---------------------------------------------------
    {
      id: "aud_0801",
      at: "2026-02-18T08:04:02+05:30",
      actor: "ai",
      event: "Refund rate breached learned band",
      detail: "Aurora Buds Pro (SKU-2481) — 9th consecutive day above the 42-day band",
      refType: "anomaly",
      refId: "anm_refund_spike",
      result: "info",
    },
    {
      id: "aud_0802",
      at: "2026-02-18T08:05:20+05:30",
      actor: "ai",
      event: "Investigation created",
      detail: "inv_1043 — refund spike on a single SKU",
      refType: "investigation",
      refId: "inv_1043",
      result: "ok",
    },
    {
      id: "aud_0803",
      at: "2026-02-18T08:11:30+05:30",
      actor: "ai",
      event: "Recommendation generated",
      detail: "Hold auto-refunds on SKU-2481 pending quality review",
      refType: "action",
      refId: "act_2042",
      result: "ok",
    },

    // ---- today: the UPI incident -----------------------------------------
    {
      id: "aud_1401",
      at: "2026-02-18T14:32:11+05:30",
      actor: "ai",
      event: "AI detected payment anomaly",
      detail: `Failure rate crossed the learned band for the 6th consecutive bucket — success ${formatPercent(s.preSuccessRate)} → ${formatPercent(s.eventSuccessRate)}`,
      refType: "anomaly",
      refId: "anm_upi_degradation",
      result: "info",
    },
    {
      id: "aud_1402",
      at: "2026-02-18T14:33:04+05:30",
      actor: "ai",
      event: "Investigation created",
      detail: "inv_1042 — UPI payment degradation, severity provisional",
      refType: "investigation",
      refId: "inv_1042",
      result: "ok",
    },
    {
      id: "aud_1403",
      at: "2026-02-18T14:34:12+05:30",
      actor: "ai",
      event: "Payment methods segmented",
      detail: "UPI isolated; card (97.6%) and netbanking (97.1%) cleared",
      refType: "investigation",
      refId: "inv_1042",
      result: "info",
    },
    {
      id: "aud_1404",
      at: "2026-02-18T14:35:01+05:30",
      actor: "ai",
      event: "Root cause identified",
      detail: `Bank X UPI degradation — ${formatPercent(s.bankShare, 0)} of failures against a ${formatPercent(s.bankBaselineShare, 0)} baseline (${s.concentrationMultiple.toFixed(1)}×)`,
      refType: "investigation",
      refId: "inv_1042",
      result: "ok",
    },
    {
      id: "aud_1405",
      at: "2026-02-18T14:36:20+05:30",
      actor: "ai",
      event: "Revenue impact calculated",
      detail: `${formatINR(s.atRisk)} at risk across ${s.affected.toLocaleString("en-IN")} payments · ${formatINR(s.recoverable)} modelled recoverable`,
      refType: "investigation",
      refId: "inv_1042",
      result: "info",
    },
    {
      id: "aud_1406",
      at: "2026-02-18T14:36:48+05:30",
      actor: "ai",
      event: "Counterfactuals scored",
      detail: "Do nothing / retry / alternate rail scored on expected recovery, cost and net benefit",
      refType: "investigation",
      refId: "inv_1042",
      result: "info",
    },
    {
      id: "aud_1407",
      at: "2026-02-18T14:37:02+05:30",
      actor: "ai",
      event: "Recovery recommendation generated",
      detail: `Offer alternate payment method to ${s.highIntentCount} high-intent customers — awaiting human approval`,
      refType: "action",
      refId: "act_2041",
      result: "ok",
    },
    {
      id: "aud_1408",
      at: "2026-02-18T14:37:03+05:30",
      actor: "policy",
      event: "Approval requirement applied",
      detail: "RECOVERY_V2 · HIGH_RISK_REQUIRES_APPROVAL — action held for a named human decision",
      refType: "policy",
      refId: "RECOVERY_V2",
      result: "blocked",
    },

    // ---- today: checkout --------------------------------------------------
    {
      id: "aud_1501",
      at: "2026-02-18T15:02:55+05:30",
      actor: "ai",
      event: "Checkout conversion breached learned band",
      detail: "3rd consecutive 20-minute bucket below the band",
      refType: "anomaly",
      refId: "anm_checkout_drop",
      result: "info",
    },
    {
      id: "aud_1502",
      at: "2026-02-18T15:03:30+05:30",
      actor: "ai",
      event: "Investigation created",
      detail: "inv_1044 — checkout conversion drop",
      refType: "investigation",
      refId: "inv_1044",
      result: "ok",
    },
    {
      id: "aud_1503",
      at: "2026-02-18T15:04:12+05:30",
      actor: "ai",
      event: "Investigation linked",
      detail: "inv_1044 linked to inv_1042 — bucket correlation 0.79, lag 0–20 minutes",
      refType: "investigation",
      refId: "inv_1044",
      result: "info",
    },

    // ---- 12 February: the reference recovery, including its failure -------
    {
      id: "aud_p101",
      at: "2026-02-12T11:14:22+05:30",
      actor: "ai",
      event: "AI detected payment anomaly",
      detail: "Netbanking degradation, 96 affected payments",
      refType: "anomaly",
      refId: "anm_20260212",
      result: "info",
    },
    {
      id: "aud_p102",
      at: "2026-02-12T11:20:03+05:30",
      actor: "ai",
      event: "Recovery recommendation generated",
      detail: "Alternate payment offer for 96 customers",
      refType: "action",
      refId: "act_2031",
      result: "ok",
    },
    {
      id: "aud_p103",
      at: "2026-02-12T11:26:44+05:30",
      actor: "merchant",
      event: "Merchant approved action",
      detail: "act_2031 approved — alternate payment offer, 96 customers",
      refType: "action",
      refId: "act_2031",
      result: "ok",
    },
    {
      id: "aud_p104",
      at: "2026-02-12T11:26:51+05:30",
      actor: "policy",
      event: "Policy validation passed",
      detail: "RECOVERY_V2 — 5 of 5 rules satisfied",
      refType: "policy",
      refId: "RECOVERY_V2",
      result: "ok",
    },
    {
      id: "aud_p105",
      at: "2026-02-12T11:27:09+05:30",
      actor: "api",
      event: "Razorpay test API called",
      detail: "POST /v1/orders → 96 recovery orders",
      refType: "action",
      refId: "act_2031",
      result: "ok",
    },
    {
      id: "aud_p106",
      at: "2026-02-12T11:27:40+05:30",
      actor: "api",
      event: "Payment retry failed",
      detail: "11 of 96 returned TEMPORARY_PAYMENT_FAILURE",
      refType: "action",
      refId: "act_2031",
      result: "failed",
    },
    {
      id: "aud_p107",
      at: "2026-02-12T11:27:41+05:30",
      actor: "policy",
      event: "Fallback policy activated",
      detail: "Retry ceiling reached for 11 payments; routed to the alternate-rail workflow",
      refType: "policy",
      refId: "RECOVERY_V2",
      result: "blocked",
    },
    {
      id: "aud_p108",
      at: "2026-02-12T11:31:09+05:30",
      actor: "api",
      event: "Payment recovered",
      detail: "64 of 96 converted · ₹84,200 recovered",
      refType: "action",
      refId: "act_2031",
      result: "ok",
    },
    {
      id: "aud_p109",
      at: "2026-02-12T11:41:09+05:30",
      actor: "ai",
      event: "Result verified",
      detail: "₹84,200 recovered against ₹79,100 modelled · verified",
      refType: "action",
      refId: "act_2031",
      result: "ok",
    },
    {
      id: "aud_p110",
      at: "2026-02-12T11:41:30+05:30",
      actor: "ai",
      event: "Memory updated",
      detail: "Recovery model recalibrated on 96 new observations",
      refType: "none",
      refId: "mem_failure_rate",
      result: "ok",
    },

    // ---- 09 February: a rejection ----------------------------------------
    {
      id: "aud_p201",
      at: "2026-02-09T16:02:40+05:30",
      actor: "ai",
      event: "Recovery recommendation generated",
      detail: "Blanket 15% recovery discount across 211 customers",
      refType: "action",
      refId: "act_2028",
      result: "ok",
    },
    {
      id: "aud_p202",
      at: "2026-02-09T16:09:12+05:30",
      actor: "merchant",
      event: "Action rejected",
      detail: "Rejected — margin impact not justified by the incremental conversion",
      refType: "action",
      refId: "act_2028",
      result: "blocked",
    },

    // ---- 07 February: a policy block --------------------------------------
    {
      id: "aud_p301",
      at: "2026-02-07T13:44:55+05:30",
      actor: "ai",
      event: "Recovery recommendation generated",
      detail: "Automatic retry across a 640-customer cohort",
      refType: "action",
      refId: "act_2026",
      result: "ok",
    },
    {
      id: "aud_p302",
      at: "2026-02-07T13:44:56+05:30",
      actor: "policy",
      event: "Policy validation blocked action",
      detail: "MAX_CUSTOMERS_PER_ACTION — cohort of 640 exceeds the 500-customer blast-radius ceiling",
      refType: "policy",
      refId: "RECOVERY_V2",
      result: "blocked",
    },
    {
      id: "aud_p303",
      at: "2026-02-07T13:46:20+05:30",
      actor: "ai",
      event: "Action re-scoped",
      detail: "Cohort narrowed to the 500 highest-expected-value payments and re-queued",
      refType: "action",
      refId: "act_2026",
      result: "info",
    },
  ];

  return events.sort((a, b) => Date.parse(b.at) - Date.parse(a.at));
}

export const AUDIT_FILTERS = [
  { key: "all", label: "All" },
  { key: "ai", label: "AI" },
  { key: "merchant", label: "Merchant" },
  { key: "api", label: "API" },
  { key: "policy", label: "Policy" },
  { key: "failure", label: "Failure" },
] as const;

export type AuditFilterKey = (typeof AUDIT_FILTERS)[number]["key"];

export function filterAuditEvents(events: AuditEvent[], key: AuditFilterKey): AuditEvent[] {
  if (key === "all") return events;
  if (key === "failure") return events.filter((e) => e.result === "failed" || e.result === "blocked");
  return events.filter((e) => e.actor === key);
}
